### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Chyi-Shin**
Drafted a copy of delicious chocolate chip pancake recipe!

## 🎯 Objective

Breakfast is the most important meal of the day - I have handpicked this recipe for you! Please let me know if there's any changes that need to be made before I add this to our repo!

## 🛠️ Changes made

Created an entirely new recipe!

## 👥 Who needs to review this Pull Request? 

@AngusMaguir3 @unakim

### CODE REVIEW

**Comment by AngusMaguir3** [comment]
@unakim @Chyi-Shin This recipe of pancakes with chocolate and strawberries looks delicious! @caitrin-hall @santip21 does this also look good to you?

**Comment by AngusMaguir3** [comment]
Reconfirming Looks good to me.

**Review by AngusMaguir3 — APPROVED** [review]

**Review by unakim — APPROVED** [review]
These changes look good to me! Let's go ahead and merge.

**Comment by Chyi-Shin** [comment]
Looks great - I'll merge!

**Comment by caitrin-hall** [comment]
this recipe looks AMAZING. i never take enough time for breakfast but i will for these choco chip pancakes! :)

**Comment by AngusMaguir3** [comment]
@santip21 Hi! Can you please write a quick message confirming that you would enjoy this breakfast! We want to make sure there is full team acceptance otherwise we should open another issue.

**Comment by santip21** [comment]
This recipe looks awesome! Well done chefs!

**Pull request merged**
