### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by santip21**
## 🎯 Objective

I am adding a recipe for tasty spaghetti

## 🛠️ Changes made

Adding ingredients, steps and notes.

## 👥 Who needs to review this Pull Request? 

@unakim @AngusMaguir3

### CODE REVIEW

**Comment by AngusMaguir3** [comment]
I don't really like this recipe... Sorry team. Does anyone else think they can spice it up?

**Comment by Chyi-Shin** [comment]
I've got a great idea to spice it up!

**Review by unakim — APPROVED** [review]
Love the overall recipe and the addition of the hot peppers! Let's merge.

**Review by AngusMaguir3 — APPROVED** [review]
Good code! That recipe now looks delicious and spicy!

**Comment by unakim** [comment]
Merging and adding to our official repo!

**Comment by caitrin-hall** [comment]
can i make this in the microwave? if so, it's gonna be dinner tonight. yum!

**Pull request merged**
