### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by unakim**
## 🎯 Objective

I'd like to address Santi's issue around insuring that our recipe is allergen-free! 

## 🛠️ Changes made

Some people may have peanut allergies so I swapped out the peanut butter with Wowbutter, which is a nut-free alternative. 

## 👥 Who needs to review this Pull Request? 

@Chyi-Shin Thoughts? I'm thinking Wowbutter is deeeelicious.

### CODE REVIEW

**Comment by Chyi-Shin** [comment]
Wowbutter is amazing - thanks @unakim! After having some Wowbutter, one might get thirsty, so I'll pair it with tangerine sparkling water for a delicious finish!

**Review by Chyi-Shin — APPROVED** [review]
Great add!

**Comment by Chyi-Shin** [comment]
I added the sparkling water - @AngusMaguir3 and @unakim , what do you think?

**Review by AngusMaguir3 — APPROVED** [review]
I'm very understanding of the nut alergy and love the idea of a nice tangerine sparkling water to wash it down!

**Pull request merged**
